module(
    name = "smoke_test",
    version = "1.0.0",
)

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "bazel_ci_rules", version = "2.1.1")
local_path_override(
    module_name = "bazel_ci_rules",
    path = "../rules",
)

rbe = use_extension("@bazel_ci_rules//:rbe_config.bzl", "rbe_config_extension")
rbe.config(
    name = "buildkite_config",
    preset = "ubuntu",
)
use_repo(rbe, "buildkite_config")
