---
pipelines:
  - name: foo
    steps:
      - command: "echo 'test'"
        label: ":llama: setup"
        agents:
          - "target=1"
        branches: "filtered_branch"
        artifact_paths: "/artifacts/automatic/upload"
        timeout: 123
        concurrency: 789
        concurrency_group: "llama-setup"
        parallelism: 456

      - command: "echo 'testing...'"
        label: "run tests"
        agents:
          - "kind=foo"
        branches: "test_branch_filtering"
        artifact_paths: "/artifact/uploading"

      - block: "wait_n_Block"
        branches: "wait_branch_filter"

      - wait
...