name: 'BCR PR Review Notifier'
description: 'Helps notify people for reviewing PRs of Bazel Central Registry.'
inputs:
  token:
    description: 'The GitHub token'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'index.js'
