name: "lockfile test"
description: "Testing lockfile"

runs:
  using: "composite"
  steps:
    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"
        chmod +x bazelisk-linux-amd64
      shell: bash
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Run update_lockfile.py
      run: |
        chmod +x ${{ github.action_path }}/update_lockfile.py
        python -u ${{ github.action_path }}/update_lockfile.py
      shell: bash
