FROM ubuntu:xenial
RUN apt-get update && apt-get install -y \
       zip g++ openjdk-8-jdk openjdk-8-source wget git unzip python python3 curl \
       ssh
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
RUN update-ca-certificates -f
